from dataclasses import dataclass, field
from typing import Optional

import torch


@dataclass
class wm_args:
    """Configuration for LIBERO policy + CtrlWorld rollout.

    This config is intentionally focused on LIBERO rollout and removes DROID-specific
    data/task scaffolding from the previous version.
    """

    # =========================
    # Model & checkpoint paths
    # =========================
    # SVD pretrained backbone initialization path.
    # Used by CtrlWorld construction for both training and rollout.
    svd_model_path: str = "/public/home/chenyuyao1/model/stable-video-diffusion-img2vid"
    clip_model_path: str = "/public/home/chenyuyao1/model/clip-vit-base-patch32"

    # Optional training resume checkpoint path.
    # Used only by train_wm.py.
    resume_ckpt_path: Optional[str] = None

    # Default world-model checkpoint path for inference / rollout.
    # rollout_wm_libero.py uses this unless overridden by CLI --ckpt_path.
    ckpt_path: str = "/public/home/chenyuyao1/code/pistar/checkpoints/Ctrl_World/libero_wm/checkpoint-10000.pt"

    # Policy checkpoint dir should be a training step directory containing `params/`
    # e.g. /.../checkpoints/pi05_star_libero/pi05_star_libero_no_state/20000
    pi_ckpt: str = "/public/home/chenyuyao1/code/pistar/checkpoints/pi05_star_libero/pi05_star_libero_no_state/20000"
    config_name: str = "pi05_star_libero_infer"
    # Manifest generated by examples/libero/get_init_gt.py
    init_gt_manifest: str = "examples/libero/init_gt_all/init_gt_manifest_all.json"

    # CtrlWorld WM-conditioning normalization stats (absolute pose 7D).
    # Required canonical keys in stat.json: wm_state_01 / wm_state_99.
    data_stat_path: str = "/public/home/chenyuyao1/code/pistar/dataset_meta_info/libero_wm/stat.json"

    # ==========================
    # World-model training defaults
    # ==========================
    # Dataset / metadata roots for train_wm.py
    dataset_root_path: str = "/public/home/chenyuyao1/code/pistar/dataset"
    dataset_meta_info_path: str = "/public/home/chenyuyao1/code/pistar/dataset_meta_info"
    dataset_names: str = "libero_wm"
    dataset_cfgs: str = "libero_wm"
    annotation_name: str = "annotation"
    latent_video_name: str = "latent_videos"

    # Training output and optimization defaults for train_wm.py
    # output_dir is for training checkpoints / validation samples.
    output_dir: str = "/public/home/chenyuyao1/code/pistar/checkpoints/Ctrl_World/libero_wm"
    # replay_output_dir is for GT-conditioned replay videos and metadata json.
    replay_output_dir: str = "/public/home/chenyuyao1/code/pistar/replay_outputs/libero_wm"
    learning_rate: float = 1e-5
    train_batch_size: int = 4
    shuffle: bool = True
    num_workers: int = 4
    max_train_steps: int = 10000
    gradient_accumulation_steps: int = 1
    max_grad_norm: float = 1.0
    checkpointing_steps: int = 1000
    validation_steps: int = 1000
    video_num: int = 1
    mixed_precision: str = "fp16"

    # Optional wandb logging for world-model training.
    wandb_enabled: bool = True
    wandb_project: str = "pistar_wm"
    wandb_run_name: Optional[str] = "pistar_wm_train"
    wandb_entity: Optional[str] = None
    # Log training scalars every N optimization steps.
    wandb_log_steps: int = 100
    # Upload local validation mp4 to wandb when validation runs.
    wandb_log_validation_video: bool = True

    # ================
    # Runtime precision
    # ================
    dtype: torch.dtype = torch.bfloat16

    # ==============================
    # CtrlWorld generation arguments
    # ==============================
    motion_bucket_id: int = 127
    fps: int = 7
    guidance_scale: float = 1.0
    num_inference_steps: int = 50
    decode_chunk_size: int = 7
    width: int = 320
    height: int = 192

    # ==========================
    # Temporal conditioning setup
    # ==========================
    num_frames: int = 5
    num_history: int = 7
    action_dim: int = 7
    text_cond: bool = True
    frame_level_cond: bool = True
    his_cond_zero: bool = False

    # =================
    # Policy interaction
    # =================
    adv_ind_input: str = "positive"
    action_horizon: int = 15
    pred_step: int = 5
    interact_num: int = 12
    # raw-time (policy/dynamics) -> WM 5Hz mapping stride.
    # With action_horizon=15 and pred_step=5, required mapping indices are:
    #   [0, 3, 6, 9, 12]
    policy_downsample_stride: int = 3

    # action semantics (fixed for pi05_star_libero(_infer)):
    # - translation/rotation channels are delta
    # - gripper channel is absolute
    gripper_max: float = 1.0
    # orientation integration for delta axis-angle:
    # - compose in quaternion space
    # - export back to axis-angle (rotvec)
    quat_delta_compose_local: bool = True

    # delta orientation diagnostics (L2 norm of axis-angle delta, radians)
    rot_delta_norm_warn: float = 0.35
    rot_delta_norm_fail: float = 0.60
    rot_delta_norm_clip: Optional[float] = None

    # action_cond normalization diagnostics
    sat_ratio_warn: float = 0.15
    sat_ratio_fail: float = 0.30
    # Saturation diagnostics mode for WM conditioning:
    # 0 = disable sat diagnostics (no compute, no logs)
    # 1 = overall sat_ratio only (warn/error logs)
    # 2 = overall sat_ratio + per-dimension detail logs
    sat_mode: int = 1

    # Unified temporal semantics on the downsampled 5Hz timeline.
    # NOTE:
    # - policy/dynamics operate on raw-time horizon (15-step chunk)
    # - world model operates on 5Hz timeline
    # - raw->5Hz pose window mapping uses indices [0, 3, 6, 9, 12]
    # For a WM window starting at t:
    #   history = [oldest, t-12, t-9, t-6, t-4, t-2, t-1]
    #   future  = [t, t+1, t+2, t+3, t+4]
    # `oldest` means the oldest available frame in current episode/buffer.
    history_use_oldest_anchor: bool = True
    history_relative_offsets: list[int] = field(default_factory=lambda: [-12, -9, -6, -4, -2, -1])
    # Shared cache length for train/rollout oldest definition.
    # - train oldest: max(0, t - wm_history_cache_len + 1)
    # - rollout buffer is truncated to this same length
    wm_history_cache_len: int = 56
    history_init_repeats: int = 4

    # Training future window stride on 5Hz timeline: [t, t+1, t+2, t+3, t+4].
    train_future_stride: int = 1

    # observation view mapping for policy input
    policy_base_camera_idx: int = 0
    policy_wrist_camera_idx: int = 1

    # ==========================
    # LIBERO task/env definition
    # ==========================
    task_suite_name: str = "libero_spatial"
    task_ids: Optional[list[int]] = None
    target_rollouts_per_task: int = 1
    seed: int = 7

    # ========================
    # rollout artifact settings
    # ========================
    task_name: str = "Rollouts_interact_pi_libero_wm"
    save_dir: str = "synthetic_traj"
    save_video: bool = True
    save_info: bool = True

    # ========================
    # Optional LeRobot exporting
    # ========================
    save_lerobot_rollout: bool = False
    rollout_repo_id: str = "ybpy/libero_wm_rollout"
    rollout_output_dir: Optional[str] = None
    rollout_overwrite: bool = False
    rollout_robot_type: str = "panda"
    rollout_fps: int = 10
    rollout_penalty_value: float = -1.0

    # ========================
    # Optional learned dynamics
    # ========================
    use_dynamics: bool = False
    dyn_ckpt_path: Optional[str] = None
    # Canonical keys: dyn_action_01/dyn_action_99/dyn_pose_01/dyn_pose_99.
    dyn_stat_path: Optional[str] = "/public/home/chenyuyao1/code/pistar/dataset_meta_info/libero_wm/stat.json"
    dyn_action_num: int = 15
    dyn_hidden_size: int = 512
    dyn_num_layers: int = 3

    def __post_init__(self):
        if self.pred_step != self.num_frames:
            raise ValueError(f"pred_step({self.pred_step}) must equal num_frames({self.num_frames})")

        if self.train_batch_size <= 0:
            raise ValueError("train_batch_size must be positive")
        if self.num_workers < 0:
            raise ValueError("num_workers must be >= 0")
        if self.max_train_steps <= 0:
            raise ValueError("max_train_steps must be positive")
        if self.gradient_accumulation_steps <= 0:
            raise ValueError("gradient_accumulation_steps must be positive")
        if self.max_grad_norm <= 0:
            raise ValueError("max_grad_norm must be positive")
        if self.checkpointing_steps <= 0:
            raise ValueError("checkpointing_steps must be positive")
        if self.validation_steps <= 0:
            raise ValueError("validation_steps must be positive")
        if self.video_num <= 0:
            raise ValueError("video_num must be positive")
        if self.wandb_log_steps <= 0:
            raise ValueError("wandb_log_steps must be positive")
        if self.wandb_enabled and len(str(self.wandb_project).strip()) == 0:
            raise ValueError("wandb_project must be non-empty when wandb_enabled=True")
        if len(str(self.replay_output_dir).strip()) == 0:
            raise ValueError("replay_output_dir must be non-empty")

        if self.policy_downsample_stride != 3:
            raise ValueError("policy_downsample_stride must be 3 for raw->5Hz mapping [0,3,6,9,12]")

        if self.target_rollouts_per_task <= 0:
            raise ValueError("target_rollouts_per_task must be positive")

        if not self.history_use_oldest_anchor:
            raise ValueError("history_use_oldest_anchor must be True for unified 5Hz semantics")

        if len(self.history_relative_offsets) != self.num_history - 1:
            raise ValueError(
                f"history_relative_offsets length ({len(self.history_relative_offsets)}) must equal num_history-1 ({self.num_history - 1})"
            )
        if len(set(self.history_relative_offsets)) != len(self.history_relative_offsets):
            raise ValueError("history_relative_offsets must not contain duplicates")
        if any(i >= 0 for i in self.history_relative_offsets):
            raise ValueError("history_relative_offsets must be < 0")
        if list(self.history_relative_offsets) != [-12, -9, -6, -4, -2, -1]:
            raise ValueError(
                "history_relative_offsets must be exactly [-12, -9, -6, -4, -2, -1] "
                "for strict train/rollout temporal alignment"
            )

        if self.history_init_repeats <= 0:
            raise ValueError("history_init_repeats must be positive")

        if self.wm_history_cache_len < self.num_history:
            raise ValueError("wm_history_cache_len must be >= num_history")

        if self.train_future_stride != 1:
            raise ValueError("train_future_stride must be 1 for future window [t, t+1, t+2, t+3, t+4]")

        if not (0.0 <= self.sat_ratio_warn <= 1.0 and 0.0 <= self.sat_ratio_fail <= 1.0):
            raise ValueError("sat_ratio_warn/sat_ratio_fail must be in [0, 1]")
        if self.sat_ratio_warn > self.sat_ratio_fail:
            raise ValueError("sat_ratio_warn must be <= sat_ratio_fail")
        if self.sat_mode not in {0, 1, 2}:
            raise ValueError("sat_mode must be one of {0, 1, 2}")

        if self.rot_delta_norm_warn <= 0 or self.rot_delta_norm_fail <= 0:
            raise ValueError("rot_delta_norm_warn/fail must be positive")
        if self.rot_delta_norm_warn > self.rot_delta_norm_fail:
            raise ValueError("rot_delta_norm_warn must be <= rot_delta_norm_fail")
        if self.rot_delta_norm_clip is not None and self.rot_delta_norm_clip <= 0:
            raise ValueError("rot_delta_norm_clip must be positive when provided")

        if self.dyn_action_num <= 0:
            raise ValueError("dyn_action_num must be positive")
        if self.dyn_hidden_size <= 0:
            raise ValueError("dyn_hidden_size must be positive")
        if self.dyn_num_layers < 2:
            raise ValueError("dyn_num_layers must be >= 2")
